export enum EnrollmentStatus {
    DRAFT = "DRAFT",
    IN_PROGRESS = "IN_PROGRESS",
    AWAITING_CLIENT = "AWAITING_CLIENT",
    AWAITING_AGENT = "AWAITING_AGENT",
    AWAITING_ADMIN = "AWAITING_ADMIN",
    AWAITING_PAYMENT = "AWAITING_PAYMENT",
    AWAITING_TRUSTEE = "AWAITING_TRUSTEE",
    COMPLETED = "COMPLETED",
    CANCELLED = "CANCELLED",
}